# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_added_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option', models.CharField(max_length=100)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dish')),
            ],
        ),
    ]
