# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_priceoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
