# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170711_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
